# Generated by Django 3.1.3 on 2021-04-20 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210402_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.FloatField()),
                ('delivery_adress', models.CharField(max_length=255)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('suggested_price', models.FloatField()),
                ('total', models.FloatField(verbose_name=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('gallons'), '*', django.db.models.expressions.F('suggested_price')))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FuelQuote',
        ),
    ]
