# Generated by Django 3.1.3 on 2021-04-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
