# Generated by Django 3.1.3 on 2021-04-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210421_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_adress',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
