# Generated by Django 3.1.3 on 2021-04-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210421_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
