# Generated by Django 3.1.3 on 2021-04-21 23:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.FloatField()),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('suggested_price', models.FloatField()),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
