# Generated by Django 3.1.3 on 2021-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210421_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
