# Generated by Django 3.1.3 on 2021-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_has_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_profile',
        ),
        migrations.AddField(
            model_name='order',
            name='has_history',
            field=models.BooleanField(default=False),
        ),
    ]
